version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cafeteria_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafeteria
      MYSQL_USER: user
      MYSQL_PASSWORD: 0000
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: cafeteria_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
